# Generated by Django 3.0.3 on 2020-09-06 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chia', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Remera',
            new_name='Articulo',
        ),
    ]
