# Generated by Django 3.0.3 on 2020-09-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chia', '0003_auto_20200906_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
