# Generated by Django 3.0.3 on 2020-09-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chia', '0005_auto_20200906_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='precio',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
