# Generated by Django 3.0.3 on 2020-09-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chia', '0006_articulo_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='precio',
            field=models.FloatField(default=0),
        ),
    ]
